import Footer from "./Footer"
import Header from "./Header"
import Profile from "./Profile"
import Sidebar from "./Sidebar"
import Messages from "./Messages"
import News from "./News"
import Music from "./Music"
import Settings from "./Settings"
import FindUsers from "./FindUsres"
export {Footer, Header, Profile, Messages, FindUsers, News, Music, Settings, Sidebar}
